# Usamos Nginx para servir el archivo estático
FROM nginx:alpine

# Copiamos nuestro index al directorio por defecto de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Exponemos el puerto 80
EXPOSE 80
